#!/usr/bin/env python3
count = 512
print(f"// Auto generated by a script. Do not edit.")
print()
for i in range(count):
    print(f"MAKE_TRAMPOLINE({i})")
print()
print("void *g_trampolines[] = {")
for i in range(count):
    print(f"    trampoline_{i},")
print("};")
print(f"#define MAX_TRAMPOLINES (sizeof(g_trampolines)/sizeof(g_trampolines[0]))")